version: '3.6'

services:
  glame:
    image: bzzim/glame
    container_name: glame
    volumes:
      - ./data:/app/data
    ports:
      - 5006:5006
    environment:
      - PASSWORD=glame_password
    restart: unless-stopped
